version: '3.9'
services:
  calender_memo:
    build: .
    volumes:
      - ./calender_memo:/calender_memo
      - ./calender_memo/node_modules:/node_modules
    working_dir: /calender_memo
    ports:
      - 3000:3000
      - 8080:8080
    command: npm run dev
    environment:
            - WATCHPACK_POLLING=true
    tty: true
  db:
    image: mysql:8.2.0
    volumes:
      - ./calender_memo/db:/var/lib/mysql
    env_file:
      - ./calender_memo/.env
    ports:
      - 3306:3306