version: '3.9'
services:
  callender_memo:
    image: node:21-alpine3.17
    volumes:
      - ./callender_memo:/callender_memo
    working_dir: /callender_memo
    ports:
      - 3000:3000
      - 8080:8080
    command: npm install && npm run dev
    tty: true

  db:
    image: mysql:8.2.0
    volumes:
      - ./callender_memo/db:/var/lib/callender_memo/db
    env_file:
      - ./callender_memo/.env
    ports:
      - 3306:3306