version: '3.9'
services:
  calendar_memo:
    build: .
    volumes:
      - ./calendar_memo:/calendar_memo
      - /node_modules:/calendar_memo/node_modules
    working_dir: /calendar_memo
    ports:
      - 3000:3000
      - 5555:5555
    environment:
            - WATCHPACK_POLLING=true
    tty: true
    command: npm run dev
  db:
    image: mysql:8.2.0
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./calendar_memo/.env
    ports:
      - 3306:3306
volumes:
    db:
    node_modules: